DROP TABLE IF EXISTS ${CITY_TABLE_NAME};

CREATE TABLE ${CITY_TABLE_NAME}(
	cityId int,
	name string
)
ROW FORMAT DELIMITED 
	FIELDS TERMINATED BY '\t' 
	LINES TERMINATED BY '\n';
	
LOAD DATA INPATH '${CITY_FILE_PATH}' INTO TABLE ${CITY_TABLE_NAME};
